### ISSUE TITLE
TypeError: Cannot read property '_traceCollector' of null

### ISSUE THREAD

**Issue by kachkaev** [apollographql/apollo-tracing-js#5]
Hi guys,

I'm trying apollo engine with apollo tracing, but am facing an odd error when trying to call `graphql` function internally via [`node-cron`](https://github.com/kelektiv/node-cron).

Here’s what `graphql(...)` returns:

```bash
{ errors:
   [ { TypeError: Cannot read property '_traceCollector' of null
    at instrumentedFieldResolver (/path/to/graphql-server/node_modules/apollo-tracing/lib/instrumentation.
js:33:40)
    at resolveFieldValueOrError (/path/to/graphql-server/node_modules/graphql/execution/execute.js:498:12)
    at resolveField (/path/to/graphql-server/node_modules/graphql/execution/execute.js:462:16)
    at /path/to/graphql-server/node_modules/graphql/execution/execute.js:284:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
       message: 'Cannot read property \'_traceCollector\' of null',
       locations: [Array],
       path: [Array] } ],
  data: { fetchProfileInfos: null } }
```
And here's where I experience the error: https://gitlab.com/kachkaev/website-graphql-server/blob/e72d236307704f3381dd7ba4d4ede3130f1bf28e/src/index.js#L108-130

Interestingly, the cron-based mutation works initially until the server is talked to from the outer word. Once some query has been made via apollo engine, a manually called `graphql()` inside the internal `cron` event fails.

What could be the cause?

I personally suspect that the issue may be related [to two nulls I'm passing into the function](https://gitlab.com/kachkaev/website-graphql-server/blob/e72d236307704f3381dd7ba4d4ede3130f1bf28e/src/index.js#L122-123), but if that's indeed the case, it's unclear what to substitute them with.

**Comment by kachkaev** [comment]
ping @martijnwalraven  (awesome [blog post on medium](https://dev-blog.apollodata.com/exposing-trace-data-for-your-graphql-server-with-apollo-tracing-97c5dd391385) BTW!)

**Comment by martijnwalraven** [comment]
Thanks! I was just working on fixing this :)

**Comment by kachkaev** [comment]
Thanks for releasing 0.0.9! Feels like this has fixed my issue, according to a couple of local experiments. I [updated the deps](https://gitlab.com/kachkaev/website-graphql-server/commit/4136be8eb6e53eedb1960b8e207fbb4cdbdb6de1) in my project and deployed the result, so will let know if the exception triggers again.

Excited to imagine what apollo engine and apollo tracing can become in 3-6 months!

**Comment by martijnwalraven** [comment]
Good to hear! I'm also pretty excited about the future :)
