### ISSUE TITLE
High data overhead with large arrays

### ISSUE THREAD

**Issue by dobesv** [apollographql/apollo-tracing-js#8]
If a query returns a long array of objects requiring many resolvers to run, and this results in a very lengthy resolvers section in the response, some large multiple in size over the original response size.  This can actually take a bit of time to serialize, which locks up the event loop for the duration (it could be one or two seconds).  Users who are directed to this server by the load balancer will have to wait much longer than usual to get a response while the tracing information is being converted to json.

I wonder if there's a way to compact the tracing information for a set of resolvers in an array, perhaps just one item for the entire array with aggregate stats like min/max/avg start/end/duration.

**Comment by evans** [comment]
Thank you for opening the issue! We're moving the tracing package to the apollo-server repository with https://github.com/apollographql/apollo-server/pull/1292, so I'll be archiving this repo.

In terms of this issue, we've moved to another reporting format with apollo-engine-reporting with https://github.com/apollographql/apollo-server/pull/1259. If you still have similar concerns, please feel free to open an issue on the apollo-server repository https://github.com/apollographql/apollo-server/issues/new and we'll be able to address them!
